services:
  sage-hub:
    build:
      context: .
    image: sage-hub:latest
    hostname: sage-hub
    container_name: sage-hub
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    networks:
      - sage-hub-network
    ports:
      - 7072:8082
    env_file:
      - .env
  postgres:
    container_name: sh-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: sage-hub
      PGDATA: /var/lib/postgresql/data
    ports:
      - 7010:5432
    volumes:
      - sh-postgres:/data/postgres
    networks:
      - sage-hub-network
    restart: unless-stopped

networks:
  sage-hub-network:
    driver: bridge
volumes:
  sh-postgres:
    driver: local
