spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /sagehub-docs
    tags-sorter: alpha
    operations-sorter: alpha
    filter: true
  api-docs:
    path: /sagehub-api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
