server:
  port: 7000

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  application:
    name: sage-hub
  jackson:
    default-property-inclusion: non_null

mailgun:
  api-key: ${MAILGUN_API_KEY}
  domain: ${MAILGUN_DOMAIN}
  from: ${MAILGUN_FROM}

# Application properties
application:
  base-url: ${BASE_URL}
  frontend: ${FRONTEND_URL}
  jwt:
    access-token:
      private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
      public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
    refresh-token:
      private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
      public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
  rate-limiter:
      max-requests: ${RATE_LIMITER_MAX_REQUESTS}
      time-interval: ${RATE_LIMITER_TIME_INTERVAL}
      reset-interval: ${RATE_LIMITER_RESET_INTERVAL}
  clean-up:
    cron: ${CLEAN_UP_CRON}
