CREATE TABLE IF NOT EXISTS _user
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by            VARCHAR(255),
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_by            VARCHAR(255),
    account_enabled       BOOLEAN                                 NOT NULL,
    client_id             UUID                                    NOT NULL,
    failed_login_attempts INTEGER,
    hashed_password       VARCHAR(255)                            NOT NULL,
    last_login            TIMESTAMP WITHOUT TIME ZONE,
    lock_time             TIMESTAMP WITHOUT TIME ZONE,
    status                VARCHAR(255)                            NOT NULL,
    username              VARCHAR(255)                            NOT NULL,
    role_id               BIGINT                                  NOT NULL,
    CONSTRAINT pk__user PRIMARY KEY (id),
    CONSTRAINT uc__user_username UNIQUE (username),
    CONSTRAINT uc__user_client_id UNIQUE (client_id)
);

CREATE TABLE IF NOT EXISTS academic_year
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    end_date   date                                    NOT NULL,
    start_date date                                    NOT NULL,
    year       INTEGER                                 NOT NULL,
    CONSTRAINT pk_academic_year PRIMARY KEY (id),
    CONSTRAINT uc_academic_year_start_date UNIQUE (start_date),
    CONSTRAINT uc_academic_year_end_date UNIQUE (end_date),
    CONSTRAINT uc_academic_year_year UNIQUE (year)
);

CREATE TABLE IF NOT EXISTS admin
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_by          VARCHAR(255),
    first_name          VARCHAR(255)                            NOT NULL,
    last_name           VARCHAR(255)                            NOT NULL,
    middle_name         VARCHAR(255),
    primary_email       VARCHAR(255)                            NOT NULL,
    profile_picture_url VARCHAR(255)                            NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_admin PRIMARY KEY (id),
    CONSTRAINT uc_admin_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS applicant
(
    id                     BIGINT                      NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by             VARCHAR(255),
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_by             VARCHAR(255),
    primary_email          VARCHAR(255)                NOT NULL,
    is_submitted           BOOLEAN                     NOT NULL,
    status                 VARCHAR(255)                NOT NULL,
    basic_info_id          BIGINT                      NOT NULL,
    contact_info_id        BIGINT                      NOT NULL,
    emergency_contact_id   BIGINT                      NOT NULL,
    user_id                BIGINT                      NOT NULL,
    year_of_application_id BIGINT,
    CONSTRAINT pk_applicant PRIMARY KEY (id),
    CONSTRAINT uc_applicant_user_id UNIQUE (user_id),
    CONSTRAINT uc_applicant_basic_info_id UNIQUE (basic_info_id),
    CONSTRAINT uc_applicant_contact_info_id UNIQUE (contact_info_id),
    CONSTRAINT uc_applicant_emergency_contact_id UNIQUE (emergency_contact_id),
    CONSTRAINT uc_applicant_primary_email UNIQUE (primary_email)
);

CREATE TABLE IF NOT EXISTS applicant_program_choices
(
    applicant_id       BIGINT NOT NULL,
    program_choices_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS applicant_result
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    index_number VARCHAR(255)                            NOT NULL,
    school_name  VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    year         INTEGER                                 NOT NULL,
    applicant_id BIGINT,
    CONSTRAINT pk_applicant_result PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS basic_info
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_by          VARCHAR(255),
    date_of_birth       date                                    NOT NULL,
    first_name          VARCHAR(255)                            NOT NULL,
    gender              VARCHAR(255)                            NOT NULL,
    last_name           VARCHAR(255)                            NOT NULL,
    marital_status      VARCHAR(255)                            NOT NULL,
    middle_name         VARCHAR(255),
    profile_picture_url VARCHAR(255)                            NOT NULL,
    title               VARCHAR(255)                            NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_basic_info PRIMARY KEY (id),
    CONSTRAINT uc_basic_info_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS contact_info
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_by      VARCHAR(255),
    street          VARCHAR(255)                            NOT NULL,
    city            VARCHAR(255)                            NOT NULL,
    region          VARCHAR(255)                            NOT NULL,
    country         VARCHAR(255)                            NOT NULL,
    phone_number    VARCHAR(255)                            NOT NULL,
    postal_address  VARCHAR(255),
    secondary_email VARCHAR(255)                            NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_contact_info PRIMARY KEY (id),
    CONSTRAINT uc_contact_info_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS course
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    code         VARCHAR(255)                            NOT NULL,
    credit_units INTEGER                                 NOT NULL,
    description  VARCHAR(255),
    name         VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id),
    CONSTRAINT uc_course_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS department
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    code       VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id),
    CONSTRAINT uc_department_code UNIQUE (code),
    CONSTRAINT uc_department_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS emergency_contact
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    street       VARCHAR(255)                            NOT NULL,
    city         VARCHAR(255)                            NOT NULL,
    region       VARCHAR(255)                            NOT NULL,
    country      VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    full_name    VARCHAR(255)                            NOT NULL,
    occupation   VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    relationship VARCHAR(255)                            NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_emergency_contact PRIMARY KEY (id),
    CONSTRAINT uc_emergency_contact_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS program
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_by    VARCHAR(255),
    cut_off       INTEGER                                 NOT NULL,
    degree        VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255),
    duration      INTEGER                                 NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    department_id BIGINT,
    CONSTRAINT pk_program PRIMARY KEY (id),
    CONSTRAINT uc_program_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS program_course
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    year       VARCHAR(255)                            NOT NULL,
    semester   VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    course_id  BIGINT                                  NOT NULL,
    program_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_program_course PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_by  VARCHAR(255),
    description VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id),
    CONSTRAINT uc_role_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS staff
(
    id                   BIGINT                      NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by           VARCHAR(255),
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_by           VARCHAR(255),
    primary_email        VARCHAR(255)                NOT NULL,
    basic_info_id        BIGINT                      NOT NULL,
    contact_info_id      BIGINT                      NOT NULL,
    emergency_contact_id BIGINT                      NOT NULL,
    user_id              BIGINT                      NOT NULL,
    CONSTRAINT pk_staff PRIMARY KEY (id),
    CONSTRAINT uc_staff_basic_info_id UNIQUE (basic_info_id),
    CONSTRAINT uc_staff_contact_info_id UNIQUE (contact_info_id),
    CONSTRAINT uc_staff_emergency_contact_id UNIQUE (emergency_contact_id),
    CONSTRAINT uc_staff_user_id UNIQUE (user_id),
    CONSTRAINT uc_staff_primary_email UNIQUE (primary_email)
);

CREATE TABLE IF NOT EXISTS student
(
    id                   BIGINT                      NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by           VARCHAR(255),
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_by           VARCHAR(255),
    primary_email        VARCHAR(255)                NOT NULL,
    basic_info_id        BIGINT                      NOT NULL,
    contact_info_id      BIGINT                      NOT NULL,
    emergency_contact_id BIGINT                      NOT NULL,
    user_id              BIGINT                      NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id),
    CONSTRAINT uc_student_basic_info_id UNIQUE (basic_info_id),
    CONSTRAINT uc_student_contact_info_id UNIQUE (contact_info_id),
    CONSTRAINT uc_student_emergency_contact_id UNIQUE (emergency_contact_id),
    CONSTRAINT uc_student_user_id UNIQUE (user_id),
    CONSTRAINT uc_student_primary_email UNIQUE (primary_email)
);

CREATE TABLE IF NOT EXISTS subject_score
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    grade        CHAR                                    NOT NULL,
    subject_name VARCHAR(255)                            NOT NULL,
    result_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_subject_score PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    value      VARCHAR(1000)                           NOT NULL,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS voucher
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by       VARCHAR(255),
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_by       VARCHAR(255),
    expires_at       TIMESTAMP WITHOUT TIME ZONE,
    pin              VARCHAR(255)                            NOT NULL,
    serial_number    BIGINT                                  NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    academic_year_id BIGINT,
    CONSTRAINT pk_voucher PRIMARY KEY (id),
    CONSTRAINT uc_voucher_serial_number UNIQUE (serial_number)
);
