
CREATE TABLE IF NOT EXISTS _user
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by            VARCHAR(255),
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_by            VARCHAR(255),
    account_enabled       BOOLEAN                                 NOT NULL,
    client_id             UUID                                    NOT NULL,
    failed_login_attempts INTEGER,
    hashed_password       VARCHAR(255)                            NOT NULL,
    last_login            TIMESTAMP WITHOUT TIME ZONE,
    lock_time             TIMESTAMP WITHOUT TIME ZONE,
    status                VARCHAR(255)                            NOT NULL,
    username              VARCHAR(255)                            NOT NULL,
    role_id               BIGINT                                  NOT NULL,
    CONSTRAINT _user_pkey PRIMARY KEY (id),
    CONSTRAINT uc__user_client_id UNIQUE (client_id),
    CONSTRAINT uc__user_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS academic_year
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    end_date   date                                    NOT NULL,
    start_date date                                    NOT NULL,
    year       INTEGER                                 NOT NULL,
    CONSTRAINT academic_year_pkey PRIMARY KEY (id),
    CONSTRAINT uc_academic_year_year UNIQUE (year),
    CONSTRAINT uc_academic_year_start_date UNIQUE (start_date),
    CONSTRAINT uc_academic_year_end_date UNIQUE (end_date)
);

CREATE TABLE IF NOT EXISTS admin
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_by      VARCHAR(255),
    first_name      VARCHAR(255)                            NOT NULL,
    middle_name     VARCHAR(255),
    last_name       VARCHAR(255)                            NOT NULL,
    primary_email   VARCHAR(255)                            NOT NULL,
    profile_picture VARCHAR(1000)                           NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    CONSTRAINT admin_pkey PRIMARY KEY (id),
    CONSTRAINT uc_admin_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS application
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by             VARCHAR(255),
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_by             VARCHAR(255),
    institution            VARCHAR(255)                            NOT NULL,
    program_pursued        VARCHAR(255)                            NOT NULL,
    start_date             date                                    NOT NULL,
    end_date               date                                    NOT NULL,
    is_submitted           BOOLEAN                                 NOT NULL,
    status                 VARCHAR(255)                            NOT NULL,
    applicant_id           BIGINT                                  NOT NULL,
    year_of_application_id BIGINT,
    CONSTRAINT application_pkey PRIMARY KEY (id),
    CONSTRAINT uc_application_applicant_id UNIQUE (applicant_id)
);

CREATE TABLE IF NOT EXISTS application_exam_results
(
    application_id  BIGINT NOT NULL,
    exam_results_id BIGINT NOT NULL,
    CONSTRAINT application_exam_results_pkey PRIMARY KEY (application_id, exam_results_id)
);

CREATE TABLE IF NOT EXISTS application_program_choices
(
    application_id     BIGINT NOT NULL,
    program_choices_id BIGINT NOT NULL,
    CONSTRAINT application_program_choices_pkey PRIMARY KEY (application_id, program_choices_id)
);

CREATE TABLE IF NOT EXISTS course
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    code         VARCHAR(255)                            NOT NULL,
    credit_units INTEGER                                 NOT NULL,
    description  VARCHAR(1000),
    name         VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT course_pkey PRIMARY KEY (id),
    CONSTRAINT uc_course_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS department
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    code       VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT department_pkey PRIMARY KEY (id),
    CONSTRAINT uc_department_code UNIQUE (code),
    CONSTRAINT uc_department_name UNIQUE (name)
);

-- CREATE TABLE IF NOT EXISTS department_program
-- (
--     department_id BIGINT NOT NULL,
--     program_id    BIGINT NOT NULL,
--     CONSTRAINT department_program_pkey PRIMARY KEY (department_id, program_id)
-- );

CREATE TABLE IF NOT EXISTS emergency_info
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    street       VARCHAR(255)                            NOT NULL,
    city         VARCHAR(255)                            NOT NULL,
    region       VARCHAR(255)                            NOT NULL,
    country      VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    full_name    VARCHAR(255)                            NOT NULL,
    occupation   VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    relationship VARCHAR(255)                            NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT emergency_info_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS exam_result
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    index_number VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    year         INTEGER                                 NOT NULL,
    student_id   BIGINT                                  NOT NULL,
    CONSTRAINT exam_result_pkey PRIMARY KEY (id),
    CONSTRAINT uc_exam_result_index_number UNIQUE (index_number)
);

CREATE TABLE IF NOT EXISTS program
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_by    VARCHAR(255),
    cut_off       INTEGER                                 NOT NULL,
    degree        VARCHAR(255)                            NOT NULL,
    description   VARCHAR(1000),
    duration      INTEGER                                 NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    department_id BIGINT,
    CONSTRAINT program_pkey PRIMARY KEY (id),
    CONSTRAINT uc_program_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS course_offering
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    year       VARCHAR(255)                            NOT NULL,
    semester   VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    course_id  BIGINT                                  NOT NULL,
    program_id BIGINT                                  NOT NULL,
    CONSTRAINT course_offering_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_by  VARCHAR(255),
    description VARCHAR(1000)                           NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (id),
    CONSTRAINT uc_role_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS staff
(
    id                BIGINT                      NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    primary_email     VARCHAR(255)                NOT NULL,
    emergency_info_id BIGINT                      NOT NULL,
    user_id           BIGINT                      NOT NULL,
    user_profile_id   BIGINT                      NOT NULL,
    CONSTRAINT staff_pkey PRIMARY KEY (id),
    CONSTRAINT uc_staff_emergency_info_id UNIQUE (emergency_info_id),
    CONSTRAINT uc_staff_primary_email UNIQUE (primary_email),
    CONSTRAINT uc_staff_user_id UNIQUE (user_id),
    CONSTRAINT uc_staff_user_profile_id UNIQUE (user_profile_id)
);

CREATE TABLE IF NOT EXISTS student
(
    id                BIGINT                      NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    primary_email     VARCHAR(255)                NOT NULL,
    emergency_info_id BIGINT                      NOT NULL,
    user_id           BIGINT                      NOT NULL,
    user_profile_id   BIGINT                      NOT NULL,
    CONSTRAINT student_pkey PRIMARY KEY (id),
    CONSTRAINT uc_student_emergency_info_id UNIQUE (emergency_info_id),
    CONSTRAINT uc_student_primary_email UNIQUE (primary_email),
    CONSTRAINT uc_student_user_id UNIQUE (user_id),
    CONSTRAINT uc_student_user_profile_id UNIQUE (user_profile_id)
);

CREATE TABLE IF NOT EXISTS subject_score
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    grade             CHAR                                    NOT NULL,
    score             DOUBLE PRECISION,
    subject           VARCHAR(255)                            NOT NULL,
    exam_result_id    BIGINT                                  NOT NULL,
    CONSTRAINT subject_score_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    value      VARCHAR(1000)                           NOT NULL,
    CONSTRAINT token_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_profile
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_by      VARCHAR(255),
    secondary_email VARCHAR(255)                            NOT NULL,
    phone_number    VARCHAR(255)                            NOT NULL,
    street          VARCHAR(255)                            NOT NULL,
    city            VARCHAR(255)                            NOT NULL,
    region          VARCHAR(255)                            NOT NULL,
    country         VARCHAR(255)                            NOT NULL,
    postal_address  VARCHAR(255),
    profile_picture VARCHAR(1000)                           NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    first_name      VARCHAR(255)                            NOT NULL,
    middle_name     VARCHAR(255),
    last_name       VARCHAR(255)                            NOT NULL,
    date_of_birth   date                                    NOT NULL,
    gender          VARCHAR(255)                            NOT NULL,
    marital_status  VARCHAR(255)                            NOT NULL,
    user_id         BIGINT,
    CONSTRAINT user_profile_pkey PRIMARY KEY (id),
    CONSTRAINT uc_user_profile_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS voucher
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by       VARCHAR(255),
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_by       VARCHAR(255),
    expires_at       TIMESTAMP WITHOUT TIME ZONE,
    pin              VARCHAR(255)                            NOT NULL,
    serial_number    BIGINT                                  NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    academic_year_id BIGINT,
    CONSTRAINT voucher_pkey PRIMARY KEY (id),
    CONSTRAINT uc_voucher_serial_number UNIQUE (serial_number)
);
